services:
  zeppelin:
    image: apache/zeppelin:0.10.0
    container_name: zeppelin
    user: "$(id -u)"
    ports:
      - "8080:8080"  # Zeppelin UI
    environment:
      ZEPPELIN_LOG_DIR: /logs
      ZEPPELIN_NOTEBOOK_DIR: /notebook
      SPARK_HOME: /opt/spark
    volumes:
      - /usr/lib/spark-current:/opt/spark
      - /home/dinithheshan-gcp-bdp-vm/bigdata-weather-analysis-sri-lanka/data:/home/data
      - /home/dinithheshan-gcp-bdp-vm/bigdata-weather-analysis-sri-lanka/docker-compose/sparkMLib/logs:/logs
      - /home/dinithheshan-gcp-bdp-vm/bigdata-weather-analysis-sri-lanka/docker-compose/sparkMLib/notebook:/notebook
    restart: unless-stopped
    
